Update pisos-monitor.yml

diff --git a/.github/workflows/pisos-monitor.yml b/.github/workflows/pisos-monitor.yml
--- a/.github/workflows/pisos-monitor.yml
+++ b/.github/workflows/pisos-monitor.yml
@@ -2,10 +2,7 @@ name: Pisos Monitor
 
 on:
   schedule:
-    # Executa cada 5 minuts
-    - cron: '*/3 * * * *'
-  
-  # Execució manual amb paràmetres personalitzables
+    - cron: '*/5 * * * *'
   workflow_dispatch:
     inputs:
       max_price:
@@ -15,6 +12,11 @@ on:
         type: string
       test_mode:
         description: 'Mode prova (només mostra logs)'
+        required: false
+        default: false
+        type: boolean
+      debug_mode:
+        description: 'Mode debug (envia missatges de cerca a Telegram)'
         required: false
         default: false
         type: boolean
@@ -38,6 +40,12 @@ jobs:
       with:
         python-version: '3.11'
     
+    - name: Debug files
+      run: |
+        pwd
+        ls -la
+        cat requirements.txt || echo "requirements.txt not found"
+    
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
@@ -49,6 +57,7 @@ jobs:
         TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
         MAX_PRICE: ${{ github.event.inputs.max_price || secrets.MAX_PRICE || '650' }}
         TEST_MODE: ${{ github.event.inputs.test_mode || 'false' }}
+        DEBUG_MODE: ${{ github.event.inputs.debug_mode || 'false' }}
       run: python main.py
     
     - name: Commit and push seen ads file
